/**
 * Map of our catalog ids -> Stripe Price ids (test mode).
 * GENERATED by scripts/create-stripe-prices.mjs — do not edit by hand.
 */
export const STRIPE_PRICE_IDS: Record<string, string> = {
  "pack_small": "price_1Te9A1EMHnfNUCi9B80vTWlv",
  "pack_medium": "price_1Te9A1EMHnfNUCi9JqaA5km4",
  "pack_large": "price_1Te9A2EMHnfNUCi9YHkhCNBk",
  "pack_jumbo": "price_1Te9A3EMHnfNUCi9NiXBeSfj",
  "plan_starter": "price_1Te9A3EMHnfNUCi9bXPNAmCA",
  "plan_growth": "price_1Te9A4EMHnfNUCi92NL0bAxd",
  "plan_pro": "price_1Te9A4EMHnfNUCi9UmCkqFwI",
  "plan_scale": "price_1Te9A5EMHnfNUCi9bDe3srQX"
};

export function priceIdFor(catalogId: string): string | undefined {
  return STRIPE_PRICE_IDS[catalogId];
}
