/**
 * Map of our catalog ids -> Stripe Price ids.
 * GENERATED by scripts/create-stripe-prices.mjs — do not edit by hand.
 */
export const STRIPE_PRICE_IDS: Record<string, string> = {
  "pack_small": "price_1TfvzvE0va9ITFCB1Zls0kP4",
  "pack_medium": "price_1TfvzwE0va9ITFCBKAniCIWg",
  "pack_large": "price_1TfvzxE0va9ITFCBVUv9GoVl",
  "pack_jumbo": "price_1TfvzxE0va9ITFCBdN4RQRZT",
  "plan_starter": "price_1TfvzyE0va9ITFCBIOVmo9LA",
  "plan_growth": "price_1TfvzyE0va9ITFCBAGKnPCyu",
  "plan_pro": "price_1TfvzzE0va9ITFCBzevy7Dp2",
  "plan_scale": "price_1Tfw00E0va9ITFCBMxnY75bo"
};

export function priceIdFor(catalogId: string): string | undefined {
  return STRIPE_PRICE_IDS[catalogId];
}
