import type {
  Design,
  DesignFields,
  DesignTheme,
  PostcardLayout,
  Template,
  TemplateKind,
} from "./types";

/** Default front layout per kind (a template can override via `layout`). */
export const DEFAULT_LAYOUT: Record<TemplateKind, PostcardLayout> = {
  just_listed: "showcase",
  just_sold: "showcase",
  coming_soon: "showcase",
  open_house: "showcase",
  market_update: "showcase",
  neighbor_intro: "intro",
};

/** Resolve the front layout for a (template, kind) pair. */
export function layoutFor(
  tpl: Template | undefined,
  kind: TemplateKind
): PostcardLayout {
  return tpl?.layout ?? DEFAULT_LAYOUT[kind];
}

/** Build a preview Design from a template (for gallery WYSIWYG previews). */
export function designFromTemplate(t: Template): Design {
  return {
    id: t.id,
    profile_id: "preview",
    name: t.name,
    source: "template",
    front_image_url: null,
    back_image_url: null,
    template_id: t.id,
    template_kind: t.kind,
    fields: { ...t.defaults, accent: t.defaults.accent || t.accent },
    created_at: "",
  } as Design;
}

/** Premium HTML print layouts (WYSIWYG preview + the only ones in the gallery). */
export const HTML_LAYOUTS = [
  "editorial",
  "banner",
  "service",
  "split",
  "minimal",
  "collage",
];
export function isHtmlLayout(fields: DesignFields | null | undefined): boolean {
  return !!fields?.layout && HTML_LAYOUTS.includes(fields.layout);
}

/** Industry category for a template (for gallery filtering). */
const TEMPLATE_CATEGORY: Record<string, string> = {
  tpl_for_sale_bold: "Real Estate",
  tpl_listing_editorial: "Real Estate",
  tpl_just_sold_bold: "Real Estate",
  tpl_coming_soon_bold: "Real Estate",
  tpl_open_house_editorial: "Real Estate",
  tpl_home_value_editorial: "Real Estate",
  tpl_meet_agent_editorial: "Real Estate",
  tpl_listing_split: "Real Estate",
  tpl_just_sold_split: "Real Estate",
  tpl_minimal_for_sale: "Real Estate",
  tpl_listing_collage: "Real Estate",
  tpl_home_services: "Lawn & Landscaping",
  tpl_cleaning_service: "Cleaning",
  tpl_hvac_service: "HVAC",
  tpl_restaurant_promo: "Restaurant",
  tpl_salon_spa_editorial: "Salon & Spa",
  tpl_grand_opening_bold: "Retail & Local",
  tpl_promo_split: "Retail & Local",
};
export function categoryOf(t: Template): string {
  return t.category || TEMPLATE_CATEGORY[t.id] || "Other";
}

/** Distinct categories across the visible (gallery) templates, ordered. */
export function templateCategories(list: Template[]): string[] {
  const seen = new Set<string>();
  for (const t of list) seen.add(categoryOf(t));
  // Real Estate first, then alphabetical.
  const all = [...seen];
  all.sort((a, b) =>
    a === "Real Estate" ? -1 : b === "Real Estate" ? 1 : a.localeCompare(b)
  );
  return all;
}

/** Default accent per kind (templates can override via `accent`). */
export const KIND_ACCENT: Record<TemplateKind, string> = {
  just_listed: "#2249c9",
  just_sold: "#0f766e",
  coming_soon: "#0ea5a4",
  open_house: "#b45309",
  market_update: "#3a63e6",
  neighbor_intro: "#9a7b4f",
};

export const KIND_LABEL: Record<TemplateKind, string> = {
  just_listed: "Just Listed",
  just_sold: "Just Sold",
  coming_soon: "Coming Soon",
  open_house: "Open House",
  market_update: "Market Update",
  neighbor_intro: "Meet Your Neighbor",
};

/** A blank field set — every personalize form starts from this. */
export function emptyFields(): DesignFields {
  return {
    headline: "",
    subhead: "",
    body: "",
    cta: "",
    property_photo_url: null,
    property_photo_url_2: null,
    property_photo_url_3: null,
    headshot_url: null,
    logo_url: null,
    testimonial: "",
    testimonial_author: "",
    price: "",
    beds: "",
    baths: "",
    sqft: "",
    property_address: "",
    event_date: "",
    event_time: "",
    agent_name: "",
    agent_phone: "",
    agent_email: "",
    accent: "",
    font: "",
    qr_url: "",
    return_name: "",
    return_company: "",
    return_line1: "",
    return_city: "",
    return_state: "",
    return_zip: "",
    nar_member: "",
    features: "",
  };
}

/**
 * Font pairings offered in the editor. Values reference the next/font CSS
 * variables loaded in the root layout. Empty/unknown → DEFAULT_FONT.
 */
export const FONTS: Record<
  string,
  { label: string; display: string; body: string }
> = {
  classic: { label: "Classic", display: "var(--font-serif)", body: "var(--font-outfit)" },
  modern: { label: "Modern", display: "var(--font-grotesk)", body: "var(--font-grotesk)" },
  editorial: { label: "Editorial", display: "var(--font-fraunces)", body: "var(--font-outfit)" },
  geometric: { label: "Geometric", display: "var(--font-outfit)", body: "var(--font-outfit)" },
};
export const DEFAULT_FONT = "classic";

/** Accent-color swatches offered in the editor (plus a custom picker). */
export const ACCENT_PRESETS = [
  "#4a7bf7",
  "#2ec4b6",
  "#6c3ce1",
  "#0f766e",
  "#2249c9",
  "#b45309",
  "#e11d48",
  "#9a7b4f",
  "#111114",
];

export const TEMPLATES: Template[] = [
  {
    id: "tpl_for_sale_bold",
    name: "For Sale · Bold",
    kind: "just_listed",
    theme: "dark",
    accent: "#4F46E5",
    layout: "showcase",
    active: true,
    defaults: {
      ...emptyFields(),
      layout: "banner",
      font: "geometric",
      accent: "#4F46E5",
      headline: "For Sale",
      subhead: "123 Anywhere St., Any City",
      property_address: "123 Anywhere St., Any City, ST 12345",
      property_photo_url:
        "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80",
      return_company: "Lopez Brown Realty",
      agent_name: "Avery Davis",
      agent_phone: "(123) 456-7890",
      body: "Get the first look before it's public. Scan to be notified the moment it goes live.",
    },
  },
  {
    id: "tpl_home_services",
    name: "Home Services · Checklist",
    kind: "neighbor_intro",
    theme: "light",
    accent: "#15803D",
    layout: "showcase",
    active: true,
    defaults: {
      ...emptyFields(),
      layout: "service",
      font: "geometric",
      accent: "#15803D",
      headline: "Professional Lawn Maintenance",
      subhead:
        "Keep your yard looking its best all year long with expert care you can rely on.",
      features:
        "Precise mowing and trimming\nWeed control and removal\nEdging for a sharp, neat finish\nSeasonal upkeep and cleanup",
      property_photo_url:
        "https://images.unsplash.com/photo-1558904541-efa843a96f01?w=1200&q=80",
      return_company: "Keithston & Partners",
      agent_phone: "(123) 456-7890",
      property_address: "123 Anywhere St., Any City",
      body: "Thinking about your yard this season? Reach out for a free quote — we'd love to help.",
    },
  },
  {
    id: "tpl_listing_editorial",
    name: "Listing · Editorial",
    kind: "just_listed",
    theme: "dark",
    accent: "#4F46E5",
    layout: "showcase",
    active: true,
    defaults: {
      ...emptyFields(),
      layout: "editorial",
      font: "editorial",
      accent: "#4F46E5",
      headline: "Just hit the market",
      subhead: "A standout home in your neighborhood",
      price: "$439,000",
      beds: "4",
      baths: "3",
      sqft: "2,480",
      property_address: "118 Maple Ridge Dr",
      property_photo_url:
        "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80",
      agent_name: "Jordan Avery",
      agent_phone: "(913) 555-0142",
      agent_email: "jordan@averyrealty.com",
      return_company: "Avery Realty Group",
      body: "A beautiful new home just hit the market nearby. Curious what your home is worth today? Scan the code for a free, no-pressure estimate.",
    },
  },
  {
    id: "tpl_just_sold_bold",
    name: "Just Sold · Bold",
    kind: "just_sold",
    theme: "dark",
    accent: "#E8324A",
    layout: "showcase",
    active: true,
    defaults: {
      ...emptyFields(),
      layout: "banner",
      font: "geometric",
      accent: "#E8324A",
      eyebrow: "Just Sold",
      headline: "Sold!",
      subhead: "Another home sold in your neighborhood",
      property_address: "123 Anywhere St., Any City",
      property_photo_url:
        "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80",
      return_company: "Avery Realty Group",
      agent_name: "Jordan Avery",
      agent_phone: "(913) 555-0142",
      body: "Thinking of making a move? Let's talk about what your home could fetch in today's market.",
    },
  },
  {
    id: "tpl_coming_soon_bold",
    name: "Coming Soon · Bold",
    kind: "coming_soon",
    theme: "dark",
    accent: "#0EA5A4",
    layout: "showcase",
    active: true,
    defaults: {
      ...emptyFields(),
      layout: "banner",
      font: "geometric",
      accent: "#0EA5A4",
      eyebrow: "Coming Soon",
      headline: "Coming Soon",
      subhead: "Get the first look before it's public",
      property_address: "123 Anywhere St., Any City",
      property_photo_url:
        "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=1200&q=80",
      return_company: "Avery Realty Group",
      agent_name: "Jordan Avery",
      agent_phone: "(913) 555-0142",
      body: "A standout home is about to hit the market nearby. Scan to be notified the moment it goes live.",
    },
  },
  {
    id: "tpl_open_house_editorial",
    name: "Open House · Editorial",
    kind: "open_house",
    theme: "dark",
    accent: "#B45309",
    layout: "showcase",
    active: true,
    defaults: {
      ...emptyFields(),
      layout: "editorial",
      font: "editorial",
      accent: "#B45309",
      headline: "Open House",
      subhead: "Come tour this beautiful home in person",
      event_date: "Sat, July 12",
      event_time: "1:00 – 4:00 PM",
      property_address: "27 Birch Hollow Ln",
      property_photo_url:
        "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80",
      return_company: "Avery Realty Group",
      agent_name: "Jordan Avery",
      agent_phone: "(913) 555-0142",
      body: "Tour the home, meet the neighbors, and see if it's the right fit. Refreshments provided.",
    },
  },
  {
    id: "tpl_home_value_editorial",
    name: "Home Value · Editorial",
    kind: "market_update",
    theme: "dark",
    accent: "#4F46E5",
    layout: "showcase",
    active: true,
    defaults: {
      ...emptyFields(),
      layout: "editorial",
      font: "editorial",
      accent: "#4F46E5",
      headline: "What's your home worth?",
      subhead: "Homes near you are selling fast",
      property_address: "Your neighborhood",
      property_photo_url:
        "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80",
      return_company: "Avery Realty Group",
      agent_name: "Jordan Avery",
      agent_phone: "(913) 555-0142",
      body: "Inventory is tight and well-priced homes are getting multiple offers. Curious what that means for you? Scan for a free, no-pressure estimate.",
    },
  },
  {
    id: "tpl_meet_agent_editorial",
    name: "Meet Your Agent · Editorial",
    kind: "neighbor_intro",
    theme: "dark",
    accent: "#9A7B4F",
    layout: "showcase",
    active: true,
    defaults: {
      ...emptyFields(),
      layout: "editorial",
      font: "editorial",
      accent: "#9A7B4F",
      headline: "Your local expert",
      subhead: "I know this neighborhood inside and out",
      property_address: "Serving your community",
      property_photo_url:
        "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80",
      return_company: "Avery Realty Group",
      agent_name: "Jordan Avery",
      agent_phone: "(913) 555-0142",
      body: "Whether you're buying, selling, or just curious about your home's value, I'd love to help. Reach out anytime.",
    },
  },
  {
    id: "tpl_cleaning_service",
    name: "Cleaning · Checklist",
    kind: "neighbor_intro",
    theme: "light",
    accent: "#0EA5A4",
    layout: "showcase",
    active: true,
    defaults: {
      ...emptyFields(),
      layout: "service",
      font: "geometric",
      accent: "#0EA5A4",
      industry: "other",
      headline: "Sparkling clean, every time",
      subhead: "Reliable home cleaning you can count on, scheduled around you.",
      features:
        "Kitchens and bathrooms\nDusting and vacuuming\nFloors and surfaces\nMove-in / move-out deep cleans",
      property_photo_url:
        "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1200&q=80",
      return_company: "Bright & Tidy Cleaning",
      agent_phone: "(123) 456-7890",
      property_address: "123 Anywhere St., Any City",
      body: "Book your first clean this month and see the difference. Reach out for a free quote.",
    },
  },
  {
    id: "tpl_hvac_service",
    name: "HVAC · Checklist",
    kind: "neighbor_intro",
    theme: "light",
    accent: "#2563EB",
    layout: "showcase",
    active: true,
    defaults: {
      ...emptyFields(),
      layout: "service",
      font: "geometric",
      accent: "#2563EB",
      industry: "other",
      headline: "Heating & cooling you can trust",
      subhead: "Fast, honest service to keep your home comfortable year-round.",
      features:
        "AC repair and tune-ups\nFurnace and heating service\nNew system installs\n24/7 emergency calls",
      property_photo_url:
        "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=1200&q=80",
      return_company: "Comfort Pros HVAC",
      agent_phone: "(123) 456-7890",
      property_address: "123 Anywhere St., Any City",
      body: "Schedule your seasonal tune-up today and save. Call us for a free estimate.",
    },
  },
  {
    id: "tpl_grand_opening_bold",
    name: "Grand Opening · Bold",
    kind: "neighbor_intro",
    theme: "dark",
    accent: "#E8324A",
    layout: "showcase",
    active: true,
    defaults: {
      ...emptyFields(),
      layout: "banner",
      font: "geometric",
      accent: "#E8324A",
      industry: "other",
      eyebrow: "Grand Opening",
      headline: "Now Open",
      subhead: "123 Anywhere St., Any City",
      property_photo_url:
        "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&q=80",
      return_company: "Your Business",
      agent_name: "Visit us today",
      agent_phone: "(123) 456-7890",
      body: "We just opened down the street and we'd love to meet you. Stop in and say hello!",
    },
  },
  {
    id: "tpl_restaurant_promo",
    name: "Restaurant Promo · Bold",
    kind: "neighbor_intro",
    theme: "dark",
    accent: "#C2410C",
    layout: "showcase",
    active: true,
    defaults: {
      ...emptyFields(),
      layout: "banner",
      font: "geometric",
      accent: "#C2410C",
      industry: "other",
      eyebrow: "Now Serving",
      headline: "20% Off Your First Visit",
      subhead: "Dine in or take out",
      property_photo_url:
        "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=80",
      return_company: "The Corner Kitchen",
      agent_name: "Open daily 11–10",
      agent_phone: "(123) 456-7890",
      body: "Bring this card in for 20% off your first order. We can't wait to feed you!",
    },
  },
  {
    id: "tpl_salon_spa_editorial",
    name: "Salon & Spa · Editorial",
    kind: "neighbor_intro",
    theme: "dark",
    accent: "#BE185D",
    layout: "showcase",
    active: true,
    defaults: {
      ...emptyFields(),
      layout: "editorial",
      font: "editorial",
      accent: "#BE185D",
      industry: "other",
      eyebrow: "Book Your Visit",
      headline: "Treat yourself",
      subhead: "A little time for you, close to home",
      property_address: "123 Anywhere St., Any City",
      property_photo_url:
        "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1200&q=80",
      return_company: "Lumière Salon & Spa",
      agent_name: "Book online or call",
      agent_phone: "(123) 456-7890",
      body: "New clients get 15% off their first appointment. Scan to book your visit today.",
    },
  },
  {
    id: "tpl_listing_split",
    name: "Just Listed · Split",
    kind: "just_listed",
    theme: "dark",
    accent: "#4F46E5",
    layout: "showcase",
    active: true,
    defaults: {
      ...emptyFields(),
      layout: "split",
      font: "geometric",
      accent: "#4F46E5",
      headline: "Just Listed",
      subhead: "A standout home in your neighborhood",
      price: "$525,000",
      beds: "4",
      baths: "3",
      sqft: "2,650",
      property_address: "118 Maple Ridge Dr",
      property_photo_url:
        "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80",
      return_company: "Avery Realty Group",
      agent_name: "Jordan Avery",
      agent_phone: "(913) 555-0142",
      body: "Just listed nearby — scan for the full gallery, details, and a private showing.",
    },
  },
  {
    id: "tpl_just_sold_split",
    name: "Just Sold · Split",
    kind: "just_sold",
    theme: "dark",
    accent: "#0F766E",
    layout: "showcase",
    active: true,
    defaults: {
      ...emptyFields(),
      layout: "split",
      font: "geometric",
      accent: "#0F766E",
      headline: "Just Sold",
      subhead: "Another home sold in your area",
      price: "Sold over asking",
      property_address: "84 Cedar Court",
      property_photo_url:
        "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80",
      return_company: "Avery Realty Group",
      agent_name: "Jordan Avery",
      agent_phone: "(913) 555-0142",
      body: "Curious what your home could sell for? The estimate is on me — just reach out.",
    },
  },
  {
    id: "tpl_minimal_for_sale",
    name: "For Sale · Minimal",
    kind: "just_listed",
    theme: "light",
    accent: "#111827",
    layout: "showcase",
    active: true,
    defaults: {
      ...emptyFields(),
      layout: "minimal",
      font: "modern",
      accent: "#111827",
      eyebrow: "For Sale",
      headline: "118 Maple Ridge Dr",
      price: "$525,000",
      property_address: "Any City, ST 12345",
      property_photo_url:
        "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80",
      return_company: "Avery Realty Group",
      agent_name: "Jordan Avery",
      agent_phone: "(913) 555-0142",
      body: "Scan the code for the full listing, photos, and a private showing.",
    },
  },
  {
    id: "tpl_listing_collage",
    name: "Listing · Collage",
    kind: "just_listed",
    theme: "light",
    accent: "#4F46E5",
    layout: "showcase",
    active: true,
    defaults: {
      ...emptyFields(),
      layout: "collage",
      font: "modern",
      accent: "#4F46E5",
      headline: "Featured Listing",
      property_address: "123 Anywhere St., Any City, ST 12345",
      price: "Asking $899,999",
      beds: "2",
      baths: "2",
      property_photo_url:
        "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1200&q=80",
      property_photo_url_2:
        "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=900&q=80",
      property_photo_url_3:
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&q=80",
      return_company: "Really Great Realty",
      agent_name: "Avery Davis",
      agent_phone: "(123) 456-7890",
      agent_email: "www.reallygreatsite.com",
      body: "Take a look at the highlights, then scan the code for the full gallery and details.",
    },
  },
  {
    id: "tpl_promo_split",
    name: "Special Offer · Split",
    kind: "neighbor_intro",
    theme: "dark",
    accent: "#9333EA",
    layout: "showcase",
    active: true,
    defaults: {
      ...emptyFields(),
      layout: "split",
      font: "geometric",
      accent: "#9333EA",
      industry: "other",
      eyebrow: "Special Offer",
      headline: "Save 20% This Month",
      subhead: "A little thank-you to our neighbors",
      property_address: "123 Anywhere St., Any City",
      property_photo_url:
        "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&q=80",
      return_company: "Your Business",
      agent_name: "Visit us today",
      agent_phone: "(123) 456-7890",
      body: "Bring this card in to claim your discount. We can't wait to see you!",
    },
  },
  {
    id: "tpl_dental_service",
    name: "Dental · New Patients",
    kind: "neighbor_intro",
    theme: "light",
    accent: "#0891B2",
    layout: "showcase",
    category: "Dental & Medical",
    active: true,
    defaults: {
      ...emptyFields(),
      layout: "service",
      font: "geometric",
      accent: "#0891B2",
      industry: "other",
      headline: "New patients welcome",
      subhead: "Gentle, modern dental care for your whole family.",
      features:
        "Cleanings and checkups\nWhitening and cosmetic\nSame-day emergencies\nMost insurance accepted",
      property_photo_url:
        "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=1200&q=80",
      return_company: "Bright Smile Dental",
      agent_phone: "(123) 456-7890",
      property_address: "123 Anywhere St., Any City",
      body: "New patients get a free first exam this month. Call to book your visit.",
    },
  },
  {
    id: "tpl_fitness_banner",
    name: "Fitness · Join Today",
    kind: "neighbor_intro",
    theme: "dark",
    accent: "#EA580C",
    layout: "showcase",
    category: "Fitness",
    active: true,
    defaults: {
      ...emptyFields(),
      layout: "banner",
      font: "geometric",
      accent: "#EA580C",
      industry: "other",
      eyebrow: "Limited Offer",
      headline: "Join Today",
      subhead: "First month free · no contracts",
      property_photo_url:
        "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&q=80",
      return_company: "Iron Works Gym",
      agent_name: "Open 5am – 11pm",
      agent_phone: "(123) 456-7890",
      body: "Your first month is on us. Bring this card in to claim your free trial.",
    },
  },
  {
    id: "tpl_event_minimal",
    name: "Event · You're Invited",
    kind: "neighbor_intro",
    theme: "light",
    accent: "#7C3AED",
    layout: "showcase",
    category: "Events",
    active: true,
    defaults: {
      ...emptyFields(),
      layout: "minimal",
      font: "editorial",
      accent: "#7C3AED",
      industry: "other",
      eyebrow: "You're Invited",
      headline: "Community Open House",
      price: "Sat · 2–5 PM",
      property_address: "123 Anywhere St., Any City",
      property_photo_url:
        "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1200&q=80",
      return_company: "Your Organization",
      agent_name: "RSVP today",
      agent_phone: "(123) 456-7890",
      body: "Join us for food, music, and fun. Scan the code to RSVP — we'd love to see you.",
    },
  },
  {
    id: "tpl_auto_service",
    name: "Auto · Service Special",
    kind: "neighbor_intro",
    theme: "light",
    accent: "#B91C1C",
    layout: "showcase",
    category: "Automotive",
    active: true,
    defaults: {
      ...emptyFields(),
      layout: "service",
      font: "geometric",
      accent: "#B91C1C",
      industry: "other",
      headline: "Service you can trust",
      subhead: "Honest, fast auto care from the pros next door.",
      features:
        "Oil changes and tune-ups\nBrakes and tires\nDiagnostics and AC\nFree multi-point inspection",
      property_photo_url:
        "https://images.unsplash.com/photo-1486006920555-c77dcf18193c?w=1200&q=80",
      return_company: "Main St. Auto",
      agent_phone: "(123) 456-7890",
      property_address: "123 Anywhere St., Any City",
      body: "Bring this card in for $20 off your next service. We'll get you back on the road.",
    },
  },
  {
    id: "tpl_pet_editorial",
    name: "Pet Care · Editorial",
    kind: "neighbor_intro",
    theme: "dark",
    accent: "#0D9488",
    layout: "showcase",
    category: "Pet Care",
    active: true,
    defaults: {
      ...emptyFields(),
      layout: "editorial",
      font: "editorial",
      accent: "#0D9488",
      industry: "other",
      eyebrow: "Pamper Your Pet",
      headline: "Happy, healthy pets",
      subhead: "Grooming, boarding, and daycare your pet will love",
      property_address: "123 Anywhere St., Any City",
      property_photo_url:
        "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=1200&q=80",
      return_company: "Paws & Co.",
      agent_name: "Book your visit",
      agent_phone: "(123) 456-7890",
      body: "New clients get 15% off the first groom. Scan to book your pet's pampering.",
    },
  },
  {
    id: "tpl_new_listing",
    name: "New Listing · Photo",
    kind: "just_listed",
    theme: "light",
    accent: "#2b2f3a",
    layout: "photo_banner",
    active: true,
    defaults: {
      ...emptyFields(),
      headline: "New Listing",
      subhead: "Just listed in your neighborhood",
      body: "A beautiful new home just hit the market nearby. Curious what your home is worth in today's market? Scan the code or reach out for a free, no-pressure estimate.",
      cta: "Scan for the full listing",
      price: "$239,000",
      property_address: "123 Anywhere St., Any City, ST 12345",
      agent_name: "Jordan Avery",
      agent_phone: "(512) 555-0142",
    },
  },
  {
    id: "tpl_newly_listed",
    name: "Newly Listed · Triptych",
    kind: "just_listed",
    theme: "light",
    accent: "#1f242e",
    layout: "triptych",
    active: true,
    defaults: {
      ...emptyFields(),
      headline: "Newly Listed",
      subhead: "Just listed in your neighborhood",
      body: "This one won't last long. Scan the code for photos, details, and a private showing.",
      cta: "Scan for the full listing",
      property_address: "123 Anywhere St., Any City, ST 12345",
      features:
        "2,100 square feet\nlisted at $524,000\n2 bedroom / 2 bath\nhuge outdoor patio\nbrand new appliances\nwalk-in closets",
      agent_name: "Jordan Avery",
      agent_phone: "(512) 555-0142",
    },
  },
  {
    id: "tpl_summary",
    name: "Listing Summary · Blush",
    kind: "just_listed",
    theme: "light",
    accent: "#b08968",
    layout: "summary",
    active: true,
    defaults: {
      ...emptyFields(),
      headline: "Summary",
      subhead: "A beautiful home, just listed",
      body: "Take a look at the highlights below, then scan the code for the full gallery and details.",
      cta: "Scan for full details",
      features:
        "4 Bedrooms\n3 Bathrooms\n4,256 sqft\nBuilt in 2017\nMountain view\nIn-ground pool\nCentral air\nFreehold",
      agent_name: "Olivia Wilson",
      agent_phone: "(512) 555-0142",
      agent_email: "hello@yoursite.com",
    },
  },
  {
    id: "tpl_aerial",
    name: "We Help You · Aerial",
    kind: "neighbor_intro",
    theme: "light",
    accent: "#2b2f3a",
    layout: "aerial",
    active: true,
    defaults: {
      ...emptyFields(),
      headline: "We help you find a home",
      subhead: "Your local brokerage",
      body: "Thinking of buying or selling in the area? Let's find the right one together. Scan the code to start.",
      cta: "Scan to get started",
      agent_name: "Beautiful Homes Realty",
      agent_phone: "(512) 555-0142",
    },
  },
  {
    id: "tpl_open_house",
    name: "Open House · Triptych",
    kind: "open_house",
    theme: "light",
    accent: "#e7d6cd",
    layout: "open_house",
    active: true,
    defaults: {
      ...emptyFields(),
      headline: "Open House",
      subhead: "You're invited",
      body: "Come tour this beautiful home in person. Refreshments provided — bring your questions and a friend. We'd love to see you there.",
      cta: "Scan for details",
      beds: "3",
      baths: "4",
      sqft: "2,895",
      property_address: "123 Anywhere St., Any City, ST",
      event_date: "Sat Jan 3rd",
      event_time: "1–3 PM",
      agent_name: "Olivia Wilson",
      agent_phone: "(512) 555-0142",
    },
  },
  {
    id: "tpl_get_in_touch",
    name: "Get in Touch · Badge",
    kind: "neighbor_intro",
    theme: "light",
    accent: "#e7d6cd",
    layout: "badge",
    active: true,
    defaults: {
      ...emptyFields(),
      headline: "Get in Touch",
      subhead: "Thinking of making a move?",
      body: "Whether you're buying, selling, or just curious about your home's value, I'd love to help. Reach out anytime.",
      cta: "Scan to connect",
      agent_name: "Olivia Wilson",
      agent_phone: "(512) 555-0142",
      agent_email: "hello@yoursite.com",
    },
  },
  {
    id: "tpl_elegant_split",
    name: "Buy or Sell · Elegant",
    kind: "neighbor_intro",
    theme: "light",
    accent: "#9a7b4f",
    layout: "elegant_split",
    active: true,
    defaults: {
      ...emptyFields(),
      headline: "Looking to buy or sell your home?",
      subhead: "Let's turn your dreams into reality.",
      body: "Whether you're ready to make a move or just curious what your home is worth today, I'd love to help. Reach out anytime for a free, no-pressure consultation.",
      cta: "Scan to start the conversation",
      agent_name: "Kimberly Nguyen",
      agent_phone: "(512) 555-0142",
    },
  },
  {
    id: "tpl_just_listed",
    name: "Just Listed",
    kind: "just_listed",
    theme: "light",
    accent: "#2249c9",
    active: false,
    defaults: {
      ...emptyFields(),
      headline: "Just Listed",
      subhead: "New on the market in your neighborhood",
      body: "A beautiful new home just hit the market nearby. Curious what your home is worth in today's market? Reach out for a free, no-pressure estimate.",
      cta: "Scan for the full listing",
      price: "$749,000",
      beds: "4",
      baths: "3",
      sqft: "2,450",
      property_address: "123 Maple Avenue",
      agent_name: "Jordan Avery",
      agent_phone: "(512) 555-0142",
    },
  },
  {
    id: "tpl_just_sold_luxe",
    name: "Just Sold · Luxe",
    kind: "just_sold",
    theme: "dark",
    accent: "#caa14a",
    active: false,
    defaults: {
      ...emptyFields(),
      headline: "I have just SOLD",
      subhead: "your neighbor's house!",
      body: "Another home sold in your neighborhood. Thinking of making a move? Let's talk about what yours could fetch.",
      cta: "Scan for a free estimate",
      price: "$1,286,000",
      beds: "4",
      baths: "3",
      sqft: "2,965",
      property_address: "7652 West Ave",
      agent_name: "Sonia Black",
      agent_phone: "(415) 555-0199",
    },
  },
  {
    id: "tpl_just_sold",
    name: "Just Sold",
    kind: "just_sold",
    theme: "light",
    accent: "#0f766e",
    active: false,
    defaults: {
      ...emptyFields(),
      headline: "Just Sold",
      subhead: "Another happy homeowner nearby",
      body: "I just helped a neighbor sell. Want to know what your home could sell for? The estimate is on me.",
      cta: "Scan for a free home estimate",
      price: "$812,000",
      beds: "3",
      baths: "2",
      sqft: "1,980",
      property_address: "456 Oak Street",
      agent_name: "Jordan Avery",
      agent_phone: "(512) 555-0142",
      testimonial: "Great agent. We sold our house in less than a month — everything went extremely well!",
      testimonial_author: "John, Client",
    },
  },
  {
    id: "tpl_coming_soon",
    name: "Coming Soon",
    kind: "coming_soon",
    theme: "bold",
    accent: "#0ea5a4",
    active: false,
    defaults: {
      ...emptyFields(),
      headline: "Coming Soon",
      subhead: "A new listing is about to hit your street",
      body: "Get the first look before it's public. Scan to be notified the moment it goes live.",
      cta: "Scan for early access",
      price: "",
      beds: "4",
      baths: "2.5",
      sqft: "2,300",
      property_address: "Your neighborhood",
      agent_name: "Jordan Avery",
      agent_phone: "(512) 555-0142",
    },
  },
  {
    id: "tpl_open_house",
    name: "Open House",
    kind: "open_house",
    theme: "bold",
    accent: "#b45309",
    active: false,
    defaults: {
      ...emptyFields(),
      headline: "Open House",
      subhead: "You're invited — stop by this weekend",
      body: "Tour the home, meet the neighbors, and see if it's the right fit. Refreshments provided.",
      cta: "Scan to RSVP",
      price: "$695,000",
      beds: "4",
      baths: "2.5",
      sqft: "2,200",
      property_address: "789 Birch Lane",
      event_date: "Saturday, June 14",
      event_time: "1:00 – 4:00 PM",
      agent_name: "Jordan Avery",
      agent_phone: "(512) 555-0142",
    },
  },
  {
    id: "tpl_market_update",
    name: "Market Update",
    kind: "market_update",
    theme: "bold",
    accent: "#3a63e6",
    active: false,
    defaults: {
      ...emptyFields(),
      headline: "Your Neighborhood Market Update",
      subhead: "Here's what's happening on your street",
      body: "Homes near you are moving fast. Inventory is tight and well-priced listings are getting multiple offers. Curious what that means for your home's value?",
      cta: "Scan for your home's value",
      price: "",
      agent_name: "Jordan Avery",
      agent_phone: "(512) 555-0142",
    },
  },
  {
    id: "tpl_neighbor_intro",
    name: "Meet Your Neighbor",
    kind: "neighbor_intro",
    theme: "light",
    accent: "#9a7b4f",
    active: false,
    defaults: {
      ...emptyFields(),
      headline: "Hi, I'm your neighbor",
      subhead: "and a local real estate agent",
      body: "You might have seen me around the neighborhood. I know this area inside and out — from HOA rules to what homes are really selling for. If you ever have a question or want a home evaluation, I hope you'll reach out!",
      cta: "Scan to say hello",
      agent_name: "Jordan Avery",
      agent_phone: "(512) 555-0142",
    },
  },
];

export function findTemplate(id: string): Template | undefined {
  return TEMPLATES.find((t) => t.id === id);
}

/** Resolve theme + accent + kind for a saved design (falls back sensibly). */
export function resolveStyle(design: Design): {
  kind: TemplateKind;
  theme: DesignTheme;
  accent: string;
  layout: PostcardLayout;
  font: string;
} {
  const kind = design.template_kind ?? "just_listed";
  const tpl = design.template_id ? findTemplate(design.template_id) : undefined;
  const overrideAccent = design.fields?.accent?.trim();
  const overrideFont = design.fields?.font?.trim();
  return {
    kind,
    theme: tpl?.theme ?? "light",
    accent: overrideAccent || tpl?.accent || KIND_ACCENT[kind],
    layout: layoutFor(tpl, kind),
    font: overrideFont && FONTS[overrideFont] ? overrideFont : DEFAULT_FONT,
  };
}
